### ISSUE TITLE
[ERROR] Install - Backend and FrontEnd

### ISSUE THREAD

**Issue by renat473** [canove/whaticket#165]
Hello,
 Error execution npm install

root@dudas-Vostro-5470:~/whaticket/backend# npm install

> sharp@0.26.3 install /root/whaticket/backend/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/whaticket/backend/node_modules/sharp/install/libvips'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/whaticket/backend/node_modules/sharp/build'
gyp ERR! System Linux 5.8.0-48-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/whaticket/backend/node_modules/sharp
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.1.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN backend@1.0.0 No description
npm WARN backend@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.26.3 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.26.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-04T02_31_15_940Z-debug.log

**Comment by renat473** [comment]
situação resolvida após a instalação fora do usuário root.
