### ISSUE TITLE
help no QrCode

### ISSUE THREAD

**Issue by danilorc** [canove/whaticket#185]
I'm not able to generate the QRcode, just keep connecting.

https://ibb.co/cyB5PvM

**Comment by danilorc** [comment]
https://imgur.com/a/wAuI5S4

**Comment by rodrigofsantos** [comment]
Você pode enviar seus dois arquivos .env aqui por favor tanto do backend quanto do frontend !!!

**Comment by danilorc** [comment]
deletei a pasta e refiz o processo agora acontece o seguinte erro; 
https://imgur.com/a/b1UuzW1
NODE_ENV=DEVELOPMENT
BACKEND_URL=http://192.168.0.142
FRONTEND_URL=https://192.168.0.142:3000
PROXY_PORT=8080
PORT=8080

DB_HOST=localhost
DB_DIALECT=mysql
DB_USER=whaticket
DB_PASS=******
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

REACT_APP_BACKEND_URL = http://192.168.0.142:8080/ 

já testei com localhost também

**Comment by rodrigofsantos** [comment]
Sua configuração esta aerrada no FRONTEND_URL=https://192.168.0.142:3000 esta https precisa ser http

**Comment by danilorc** [comment]
consegui logar novamente obrigado!

porém voltei ao primeiro problema segue o log backend e print do navegador.


> backend@1.0.0 start /home/danilo/whaticket/backend
> nodemon dist/server.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dist/server.js`
[1622001851510] INFO: Server started on port: 8080
[1622001853229] INFO: Client Connected
[1622001853432] INFO: Client Connected
[1622001853477] INFO: A client joined notification channel
[1622001855184] INFO: Client Connected
[1622001870689] INFO: Client disconnected
[1622001870691] INFO: Client disconnected
[1622001870693] INFO: Client disconnected
[1622001885194] INFO: Client Connected
[1622001885218] INFO: A client joined notification channel
[1622001886187] INFO: Client Connected
[1622001887185] INFO: Client Connected
(node:4812) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded
    at new WaitTask (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
    at Frame.waitForSelector (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    at Page.waitForSelector (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
    at getQrCode (/home/danilo/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:127:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1622002069830] INFO: Client disconnected
[1622002069834] INFO: Client disconnected
[1622002069834] INFO: Client disconnected
[1622002077629] INFO: Client Connected
[1622002077705] WARN:
    message: "Invalid token. We'll try to assign a new one on next request"
    statusCode: 403
[1622002077801] INFO: Client Connected
[1622002077887] WARN:
    message: "Invalid token. We'll try to assign a new one on next request"
    statusCode: 403
[1622002077897] INFO: Client Connected
[1622002077905] INFO: Client Connected
[1622002078047] INFO: Client disconnected
[1622002078610] INFO: Client Connected
[1622002078627] INFO: Client disconnected
[1622002078648] INFO: Client Connected
[1622002078664] WARN:
    message: "Invalid token. We'll try to assign a new one on next request"
    statusCode: 403
[1622002078696] INFO: A client joined notification channel
[1622002078736] WARN:
    message: "Invalid token. We'll try to assign a new one on next request"
    statusCode: 403
[1622002078923] INFO: Client Connected
[1622002078940] INFO: Client Connected
[1622002079050] INFO: A client joined notification channel
[1622002579499] INFO: Client Connected
[1622002579555] INFO: Client Connected
[1622002579579] INFO: A client joined to open tickets channel.
[1622002579601] INFO: A client joined to pending tickets channel.
[1622002581187] INFO: Client disconnected
[1622002581189] INFO: Client disconnected
[1622002582999] INFO: Client Connected
[1622002588014] INFO: Client disconnected
(node:4812) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded
    at new WaitTask (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:312:29)
    at Frame.waitForSelector (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    at Page.waitForSelector (/home/danilo/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1285:33)
    at getQrCode (/home/danilo/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:127:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1622002625361] INFO: Client disconnected
[1622002625363] INFO: Client disconnected
[1622002625364] INFO: Client disconnected
[1622002625509] INFO: Client disconnected
[1622002625511] INFO: Client disconnected
[1622002625512] INFO: Client disconnected
[1622002673196] WARN:
    message: "ERR_SESSION_EXPIRED"
    statusCode: 401
[1622002673244] INFO: Client Connected
[1622002686970] WARN:
    message: "ERR_INVALID_CREDENTIALS"
    statusCode: 401
[1622002693676] INFO: Client disconnected
[1622002694311] INFO: Client Connected
[1622002694390] INFO: Client Connected
[1622002694407] INFO: Client Connected
[1622002694447] INFO: Client Connected
[1622002694450] INFO: Client Connected
[1622002694857] INFO: A client joined notification channel
[1622002694879] INFO: A client joined to open tickets channel.
[1622002694898] INFO: A client joined to pending tickets channel.
[1622002698763] INFO: Client disconnected
[1622002698764] INFO: Client disconnected

https://imgur.com/a/tLezzMn

**Comment by rodrigofsantos** [comment]
Você vai precisar reinstalar o npm remove a pasta node_modules e no diretório do bakend e do frontend instala ele novamente npm install 
se aparecer algum erro manda aqui por favor !! pode ser necessário apos fazer isso digitar:
#npm install --force
#npm audit fix --force
nos dois diretorios !!
Não se esqueça que voce não pode usar o root e nem rodar o npm start com sudo !!!

**Comment by hueltonsantos** [comment]
Podem me ajudar?
