### ISSUE TITLE
Erro ao tentar colocar o QR CODE

### ISSUE THREAD

**Issue by samueldietrick** [canove/whaticket#219]
![image](https://user-images.githubusercontent.com/69129398/130323566-5cc6f530-8bee-4ee2-a4f0-08855182e5b9.png)

**Comment by Marcosschwaab** [comment]
Consegui funcionar sem problemas no mint com instalação limpa, antes estava tentando rodar o WSL2 no Windows 10 que ainda não funcionou, muito obrigada pela ajuda Rodrigo.

**Comment by rodrigofsantos** [comment]
Disponha!

**Comment by leandroslemes** [comment]
Infelizmente estou com este mesmo problema e atualizei tudo e nada. Qual melhor saida?

[1631980379569] INFO: Client disconnected
[1631980379571] INFO: Client disconnected
UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0918/155121.241566:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See ht                                                  tps://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/root/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:1                                                  87:68)
    at Interface.emit (events.js:412:35)
    at Interface.emit (domain.js:532:15)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:412:35)
    at Socket.emit (domain.js:532:15)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing i                                                  nside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To te                                                  rminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https:/                                                  /nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejecti                                                  ons that are not handled will terminate the Node.js process with a non-zero exit code.
 UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process![1631980379565]TROUBLESHOOTING^Z
[1]+  Stopped                 npm start
root@whatsapp-ticket:~/whaticket/backend# node -v
v14.17.6
root@whatsapp-ticket:~/whaticket/backend#

**Comment by maxivane** [comment]
Estou com mesmo problema do leandro. alguem conseguiu resolver?

**Comment by leandroslemes** [comment]
> Estou com mesmo problema do leandro. alguem conseguiu resolver?

Isso ocorre porque você está executando o projeto com o usuário root. Utilize um usuário comum que tudo deve funcionar. Em questão do QRCODE consegui resolver com isso.

**Comment by kaoehenrik** [comment]
Ola, boa noite a todos, fiz a instalação limpa e tudo ok, porem não esta gerando o Qr Code, ja pesquisei muito aqui e não entendi como que resolvo isso, tem algum que poderia me dar uma força?
![sss](https://user-images.githubusercontent.com/79760134/184518775-ec5010e9-474d-46b8-8b67-4220e9595e2a.png)

**Comment by Marcosschwaab** [comment]
Qual ambiente você está usando, para mim funcionou com tudo instalado em um Linux nativo, no WSL2 não funcionava a geração do QRcode.

**Comment by raffus** [comment]
Tenta rodar novamente sem ser como ROOT. Aqui deu certo! :)
