### ISSUE TITLE
Erro ao Buildar Frontend

### ISSUE THREAD

**Issue by redealpha** [canove/whaticket#261]
Estou tendo problemas ao buildar o Frontend

Failed to compile.

./src/routes/Route.js
Syntax error: Unexpected token (12:4)

  10 |  if (!isAuth && isPrivate) {
  11 |          return (
> 12 |                  <>
     |                        ^
  13 |                          {loading && <BackdropLoading />}
  14 |                          <Redirect to={{ pathname: "/login", state: { from: rest.location } }} />
  15 |                  </>

Já refiz a pasta node_modules, mas não builda

**Comment by tibehrius** [comment]
Mesmo problema aqui...

**Comment by redealpha** [comment]
Consegui contornar o problema da seguinte forma:

1. Refiz a pasta node_modules, rodando o npm como super user `sudo npm install`
2. Na hora de buildar, deu erro de ` Attempted import error: 'create Theme' is not exported from '@material-ui/core/styles'.`.
3. Para contornar o erro, editei o arquivo src/App.js e alterei o import para `import { createMuiTheme, ThemeProvider } from "@material-ui/core/styles";`
4. E rodei novamente o comando `npm run build` e funcionou!!

**Comment by redealpha** [comment]
> Mesmo problema aqui...

Veja se consegue fazer desta forma

**Comment by tibehrius** [comment]
O erro que estou recebendo é esse: 

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2021-10-05T16_59_02_267Z-debug.log
`

**Comment by tibehrius** [comment]
Conteúdo do log informado:

`deploy@waticket:~/whaticket/frontend/src$ cat /home/deploy/.npm/_logs/2021-10-05T16_59_02_267Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.15
3 info using node@v14.18.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/whaticket/frontend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle frontend@0.1.0~build: CWD: /home/deploy/whaticket/frontend
10 silly lifecycle frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle frontend@0.1.0~build: Failed to exec build script
13 verbose stack Error: frontend@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid frontend@0.1.0
15 verbose cwd /home/deploy/whaticket/frontend/src
16 verbose Linux 4.15.0-153-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.18.0
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the frontend@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
deploy@waticket:~/whaticket/frontend/src$
`

**Comment by redealpha** [comment]
> O erro que estou recebendo é esse:
> 
> `npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! frontend@0.1.0 build: `react-scripts build` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the frontend@0.1.0 build script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/deploy/.npm/_logs/2021-10-05T16_59_02_267Z-debug.log `

Este erro parece ser um problema com o node.  Talvez possa corrigir pegando a versão mais recente do node. Tente estes passos:

1. `sudo npm cache clean -f`
2. `sudo npm install -g n`
3. `sudo n stable`
4. `rm -rf node_modules`
5. `npm node_modules`
