### ISSUE TITLE
Error when authenticated done

### ISSUE THREAD

**Issue by marlon33** [canove/whaticket#3]
```
(node:3464) UnhandledPromiseRejectionWarning: Error: Evaluation failed: t
    at ExecutionContext._evaluateInternal (C:\Bots\whaticket-master\backend\node
_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\Bots\whaticket-master\backend\node_mo
dules\puppeteer\lib\ExecutionContext.js:33:16)
    at async Client.sendPresenceAvailable (C:\Bots\whaticket-master\backend\node
_modules\whatsapp-web.js\src\Client.js:537:16)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Bots\whaticket-master\backend\node_modul
es\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (C:\Bots\whaticket-master\backend\node_modules\puppetee
r\lib\DOMWorld.js:89:24)
  -- ASYNC --
    at Frame.<anonymous> (C:\Bots\whaticket-master\backend\node_modules\puppetee
r\lib\helper.js:94:19)
    at Page.evaluate (C:\Bots\whaticket-master\backend\node_modules\puppeteer\li
b\Page.js:612:14)
    at Page.<anonymous> (C:\Bots\whaticket-master\backend\node_modules\puppeteer
\lib\helper.js:95:27)
    at Client.sendPresenceAvailable (C:\Bots\whaticket-master\backend\node_modul
es\whatsapp-web.js\src\Client.js:537:35)
    at Client.<anonymous> (C:\Bots\whaticket-master\backend\src\libs\wbot.js:69:
9)
(node:3464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 4)
(node:3464) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector
 "canvas" failed: timeout 45000ms exceeded
    at new WaitTask (C:\Bots\whaticket-master\backend\node_modules\puppeteer\lib
\DOMWorld.js:388:34)
    at DOMWorld._waitForSelectorOrXPath (C:\Bots\whaticket-master\backend\node_m
odules\puppeteer\lib\DOMWorld.js:313:26)
    at DOMWorld.waitForSelector (C:\Bots\whaticket-master\backend\node_modules\p
uppeteer\lib\DOMWorld.js:296:21)
    at Frame.waitForSelector (C:\Bots\whaticket-master\backend\node_modules\pupp
eteer\lib\FrameManager.js:384:51)
    at Frame.<anonymous> (C:\Bots\whaticket-master\backend\node_modules\puppetee
r\lib\helper.js:95:27)
    at Page.waitForSelector (C:\Bots\whaticket-master\backend\node_modules\puppe
teer\lib\Page.js:799:33)
    at Timeout.getQrCode (C:\Bots\whaticket-master\backend\node_modules\whatsapp
-web.js\src\Client.js:110:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 5)
(node:3464) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector
 "canvas" failed: timeout 45000ms exceeded
    at new WaitTask (C:\Bots\whaticket-master\backend\node_modules\puppeteer\lib
\DOMWorld.js:388:34)
    at DOMWorld._waitForSelectorOrXPath (C:\Bots\whaticket-master\backend\node_m
odules\puppeteer\lib\DOMWorld.js:313:26)
    at DOMWorld.waitForSelector (C:\Bots\whaticket-master\backend\node_modules\p
uppeteer\lib\DOMWorld.js:296:21)
    at Frame.waitForSelector (C:\Bots\whaticket-master\backend\node_modules\pupp
eteer\lib\FrameManager.js:384:51)
    at Frame.<anonymous> (C:\Bots\whaticket-master\backend\node_modules\puppetee
r\lib\helper.js:95:27)
    at Page.waitForSelector (C:\Bots\whaticket-master\backend\node_modules\puppe
teer\lib\Page.js:799:33)
    at Timeout.getQrCode (C:\Bots\whaticket-master\backend\node_modules\whatsapp
-web.js\src\Client.js:110:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 6)
```

other thing, i start this on aws vps, but the server was calling the privete IP note the public ip, how can i fix it?
![image](https://user-images.githubusercontent.com/41172965/90587052-dd34b700-e1ae-11ea-8124-fc6fa31c960c.png)

**Comment by canove** [comment]
About the first error, it may be related to whatsapp authentication. Some features in system try to use "wbot", and if its still in "authenticating" mode (before read QRcode), it throw an error. I will try to solve this in a few days.

About running it in a VPS, you need to build frontend app (in frontend folder, run: `npm run build`). It will create a folder called "build", that you can server with apache or nginx.
You should also change cors setting in `backend\src\app.js` to improve security.

Note: Its not tested it in a production environment, and I'm not sure that its safe to use.

**Comment by marlon33** [comment]
I did it, change the ip's 'localhost' to 'ipv4 of vps' but still have error,
` Failed to load resource: net::ERR_CONNECTION_REFUSED
localhost:8080/auth/login:1 `

i already change the ip's, but still connection was localhost, and i'm trying fix it tks

**Comment by marlon33** [comment]
I solvedd this problem, the host did not connect to the server, because my vps ipv4 is private, so, i used a no-ip to connect host > server
