### ISSUE TITLE
Erro em mensagem de boaas vindas.

### ISSUE THREAD

**Issue by italow6** [canove/whaticket#330]
`node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

DatabaseError [SequelizeDatabaseError]: Incorrect string value: '\xE2\x80\x8EBom...' for column `whaticket`.`tickets`.`lastMessage` at row 1
    at Query.formatError (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\sequelize\lib\dialects\mysql\query.js:244:16)
    at Execute.handler [as onResult] (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\commands\command.js:36:14)
    at Connection.handlePacket (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  parent: Error: Incorrect string value: '\xE2\x80\x8EBom...' for column `whaticket`.`tickets`.`lastMessage` at row 1
      at Packet.asError (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Execute.execute (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
    errno: 1366,
    sqlState: '22007',
    sqlMessage: "Incorrect string value: '\\xE2\\x80\\x8EBom...' for column `whaticket`.`tickets`.`lastMessage` at row 1",
    sql: 'UPDATE `Tickets` SET `lastMessage`=?,`updatedAt`=? WHERE `id` = ?',
    parameters: [
      '‎Bom dia, escolha o setor que deseja ser atendido.\n' +
        '*1* - Financeito\n' +
        '*2* - Suporte\n',
      '2022-01-05 11:43:36',
      44
    ]
  },
  original: Error: Incorrect string value: '\xE2\x80\x8EBom...' for column `whaticket`.`tickets`.`lastMessage` at row 1
      at Packet.asError (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Execute.execute (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\adiministrator\Downloads\whaticket\whaticket\backend\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
    errno: 1366,
    sqlState: '22007',
    sqlMessage: "Incorrect string value: '\\xE2\\x80\\x8EBom...' for column `whaticket`.`tickets`.`lastMessage` at row 1",
    sql: 'UPDATE `Tickets` SET `lastMessage`=?,`updatedAt`=? WHERE `id` = ?',
    parameters: [
      '‎Bom dia, escolha o setor que deseja ser atendido.\n' +
        '*1* - Financeito\n' +
        '*2* - Suporte\n',
      '2022-01-05 11:43:36',
      44
    ]
  },
  sql: 'UPDATE `Tickets` SET `lastMessage`=?,`updatedAt`=? WHERE `id` = ?',
  parameters: [
    '‎Bom dia, escolha o setor que deseja ser atendido.\n' +
      '*1* - Financeito\n' +
      '*2* - Suporte\n',
    '2022-01-05 11:43:36',
    44
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
`

Erro ao enviar mensagem de boas vindas.
Como resolver?

**Comment by w3nder** [comment]
O bancos de dados e as tabelas devem ter conjunto de caracteres utf8mb4 e agrupamento utf8mb4_unicode_ci.
se não, as mensagem que tem emoji não vai gravar no banco de dados.

**Comment by italow6** [comment]
Resolvido, era o conjunto de caracteres mesmo, obg.
