### ISSUE TITLE
Erro ao executar Backend - Carregar QR Code

### ISSUE THREAD

**Issue by tpmr8** [canove/whaticket#345]
Olá. Eu fiz a instalação hoje. Ao acessar o frontend, vi que não carregava o QR CODE para adicionar o WhatsApp. Então executei **npm run dev:server** e recebi este erro:

> backend@1.0.0 dev:server
> ts-node-dev --respawn --transpile-only --ignore node_modules src/server.ts

[INFO] 19:55:16 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.0.3)
Error: listen EADDRINUSE: address already in use :::7777
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at Function.listen (/var/www/public_html/whaticket/backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/var/www/public_html/whaticket/backend/src/server.ts:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/var/www/public_html/whaticket/backend/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-8371329644392447.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-8371329644392447.js:71:20)
    at Object.nodeDevHook [as .ts] (/var/www/public_html/whaticket/backend/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/public_html/whaticket/backend/node_modules/ts-node-dev/lib/wrap.js:104:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/var/www/public_html/whaticket/backend/node_modules/source-map-support/source-map-support.js:568:25)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
**[ERROR]** 19:55:19 Error: listen EADDRINUSE: address already in use :::**7777**

Eu já troque para várias portas e o erro continua. 
Ao executar sudo lsof -i :7777 eu recebo isto:

COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node\x20/ 53693     root   19u  IPv6 764854      0t0  TCP localhost:7777->localhost:53712 (ESTABLISHED)
node\x20/ 53693     root   20u  IPv6 734692      0t0  TCP *:7777 (LISTEN)
node\x20/ 53693     root   21u  IPv6 764849      0t0  TCP localhost:7777->localhost:53708 (ESTABLISHED)
node\x20/ 53693     root   22u  IPv6 762847      0t0  TCP localhost:7777->localhost:53716 (ESTABLISHED)
apache2   53909 www-data   39u  IPv4 765685      0t0  TCP localhost:53708->localhost:7777 (ESTABLISHED)
apache2   53911 www-data   39u  IPv4 770273      0t0  TCP localhost:53712->localhost:7777 (ESTABLISHED)
apache2   53955 www-data   39u  IPv4 764857      0t0  TCP localhost:53716->localhost:7777 (ESTABLISHED)

Alguém já enfrentou algo assim?

**Comment by tpmr8** [comment]
Consegui resolver.

**Comment by lucassumendes** [comment]
como resolveu?
