### ISSUE TITLE
Nao loga

### ISSUE THREAD

**Issue by phsilvasantos** [canove/whaticket#372]
[1644529479649] ERROR: Error starting whatsapp session.
    Error: Error starting whatsapp session.
        at C:\Users\Paulo\Desktop\bot\backend\dist\libs\wbot.js:93:24
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Paulo\Desktop\bot\backend\dist\libs\wbot.js:5:58)

![image](https://user-images.githubusercontent.com/13142561/153501780-9920ae89-4bd3-4c75-84d8-952beb34bfec.png)

**Comment by phsilvasantos** [comment]
resolvido porem quando chamo ou falo ele nao responde nd
