### ISSUE TITLE
 session is not supported for MultiDevice-enabled 

### ISSUE THREAD

**Issue by athila755** [canove/whaticket#417]
(node:1430) UnhandledPromiseRejectionWarning: Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
    at LegacySessionAuth.getAuthEventPayload (/home/whats/whaticket/backend/node_modules/whatsapp-web.js/src/authStrategies/LegacySessionAuth.js:57:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.initialize (/home/whats/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:217:34)
(node:1430) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1430) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by l4p84** [comment]
Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

**Comment by kozac** [comment]
https://github.com/canove/whaticket/issues/401#issuecomment-1057989671  < solved
