### ISSUE TITLE
Error adding connection

### ISSUE THREAD

**Issue by almando** [canove/whaticket#436]
### Error adding new conection

```  
errno: -39,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path:
   '/home/user/containers/whaticket/backend/.wwebjs_auth/session-bd_9' }
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
    at ExecutionContext._evaluateInternal (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
    at ExecutionContext.evaluate (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
    at DOMWorld.evaluate (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at Object.window.WWebJS.getChats (__puppeteer_evaluation_script__:350:36)
    at __puppeteer_evaluation_script__:2:40
    at ExecutionContext._evaluateInternal (/home/user/containers/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by YosefAdPro** [comment]
See the solution hare
https://whaticket.online/d/158-erro-nodemon-app-crashed/8

**Comment by YosefAdPro** [comment]
See the solution here
https://whaticket.online/d/158-erro-nodemon-app-crashed/8
