### ISSUE TITLE
Error after qrcode reading

### ISSUE THREAD

**Issue by alessandrosales** [canove/whaticket#437]
![image](https://user-images.githubusercontent.com/8078636/172678859-6c35ea40-987c-4e1a-b47a-79e0e9e693e4.png)

`
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at Object.window.WWebJS.getChats (__puppeteer_evaluation_script__:350:36)
    at __puppeteer_evaluation_script__:2:40
    at ExecutionContext._evaluateInternal (/home/alessandro/Workspace/eric-herison/sacmaisbasico/backend/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ExecutionContext.evaluate (/home/alessandro/Workspace/eric-herison/sacmaisbasico/backend/node_modules/whatsapp-web.js/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.getChats (/home/alessandro/Workspace/eric-herison/sacmaisbasico/backend/node_modules/whatsapp-web.js/src/Client.js:633:21)
`

**Comment by YosefAdPro** [comment]
See the solution here
https://whaticket.online/d/158-erro-nodemon-app-crashed/8

**Comment by alessandrosales** [comment]
Page not found

![image](https://user-images.githubusercontent.com/8078636/172941178-878fd461-3d8c-43a4-82a3-8fad95ceb4e7.png)
