### ISSUE TITLE
Backend dont starts after first reboot

### ISSUE THREAD

**Issue by pedroh-dev255** [canove/whaticket#439]
after restart the aplication the backend stop to start!

error:
c:\whaticket\backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at Object.window.WWebJS.getChats (__puppeteer_evaluation_script__:350:36)
    at __puppeteer_evaluation_script__:2:40
    at ExecutionContext._evaluateInternal (C:\whaticket\backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (C:\whaticket\backend\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.getChats (C:\whaticket\backend\node_modules\whatsapp-web.js\src\Client.js:633:21)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by CristianoMZN** [comment]
I can help you: https://whaticket.online/d/158-erro-nodemon-app-crashed/8

**Comment by CristianoMZN** [comment]
It can help you: https://github.com/pedroslopez/whatsapp-web.js/pull/1494/files

**Comment by imanudin11** [comment]
Hi,
I have similar problem and this is what I do

# on whaticket/backend

npm install whatsapp-web.js

HTH

**Comment by pedroh-dev255** [comment]
That's sove my problem, thx u.
