### ISSUE TITLE
Enviar video mp4

### ISSUE THREAD

**Issue by marciocvitor** [canove/whaticket#455]
Estou com problema para enviar vídeo mp4, apresenta a msg: **_Erro ao enviar mensagem do WhatsApp, Verifique a conexão._**

![image](https://user-images.githubusercontent.com/82884631/183773438-dafc933a-7045-4f40-bfb6-4e8b56f1de1c.png)

Consigo enviar normalmente, pdf, mp3, documento, msg, etc...

**Versão:** "whatsapp-web.js": "^1.17.1"

**_Log do erro._**

Error: Evaluation failed: N
    at ExecutionContext._evaluateInternal (whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.sendMessage (whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:601:28)
[1660084163695] WARN:
    message: "ERR_SENDING_WAPP_MSG"
    statusCode: 400

**Comment by GabrielMaestre** [comment]
Leia a descrição do projeto:

Send and receive message ✅
Send media (images/audio/documents) ✅

Não é possível enviar vídeo, e certas coisas necessita-se de certificado SSL, mas dúvido que mp4 funcione.

**Comment by marciocvitor** [comment]
Ok, obrigado.
