### ISSUE TITLE
doesnt start a whatsapp session

### ISSUE THREAD

**Issue by faletotal** [canove/whaticket#80]
(node:6718) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at __puppeteer_evaluation_script__:5:51
    at ExecutionContext._evaluateInternal (/home/vertex/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/vertex/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async Client.initialize (/home/vertex/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:145:9)
(node:6718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by developerdevice** [comment]
It's an error with whatsapp-js dependency, wait for update.

**Comment by developerdevice** [comment]
> It's an error with whatsapp-js dependency, wait for update.

The bug was fixed, please update according the doc and close the issue.

**Comment by ldurans** [comment]
Updated v1.11.1 - WhatsApp Web v2.2
https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.11.1

**Comment by canove** [comment]
fixed by https://github.com/canove/whaticket/commit/96bdb2aea670dd9adc4501c0d068132549c4ca4e
